name: my_calculator
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=2.19.0 <3.0.0'

dependencies:
  audioplayers: ^4.1.0
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.3.6
  intl: ^0.18.1
  math_expressions: ^2.4.0
  sizer: ^2.0.15

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/
